name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [release/master]
  # run it during pull request
  pull_request:
    branches: [release/master]

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./
          # Note: tags has to be all lower-case
          tags: |
            cuza/erupe:latest
            cuza/erupe:${{ steps.date.outputs.date }}
            cuza/erupe:${{ github.event.head_commit.id }}
            ghcr.io/cuza/erupe:latest
            ghcr.io/cuza/erupe:${{ steps.date.outputs.date }}
            ghcr.io/cuza/erupe:${{ github.event.head_commit.id }}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/release/master' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
